[pytest]

#CMD logging (Set warning due to clear cmd output)
log_cli = 1
log_cli_level = INFO
log_cli_date_format = %Y-%m-%d %H:%M:%S
log_cli_format = %(asctime)s |%(levelname)s| |[%(filename)s:%(lineno)d][%(funcName)s]| %(message)s

#Test case naming rules
python_files = test_* *_test test*
python_classes = Test* test*
python_functions = test_* test*

#Recursive discovery rules for test case
norecursedirs = data framework module page log reports tools

markers =
    P1: Priority 1(Cube 官網 網銀 Robo)
    P2: Priority 2(Cube 官網 網銀 Robo)
    P3: Priority 3(Cube 官網 網銀 Robo)
    debug: for debug use
    android: android platform
    ios: ios platform
    cube: cube product
    login: 登入(Cube 網銀 Robo)
    financial_overview: 帳務總覽(Cube)
    twd: 臺幣(Cube 網銀)
    foreign_currency: 外幣(Cube 網銀)
    setting: 設定(Cube 網銀)
    credit_card: 信用卡(Cube 官網 網銀)
    payment: 繳費(Cube 官網 網銀)
    loan: 貸款(Cube 官網 網銀)
    invest: 投資(Cube 網銀)
    open_account: 開戶(Cube 官網)
    face_id: 人臉相關(Cube)
    video_chat: 視訊客服(Cube)
    push_notification: 推播(Cube)
    insurance: 保險(Cube 網銀)
    language: 多語系架構(Cube)
    other: 其他(Cube 官網 網銀)
    gbi: GBI全球債券指數(Robo)
    tbi: TBI策略式投資組合(Robo)
    ilp: ILP(Robo)
    create_order: 申購 GBI/TBI/ILP(Robo)
    manage: 管理 GBI/TBI(Robo)
    delete: 刪除 GBI/TBI(Robo)
    redeem: 贖回 GBI/TBI(Robo)
    rebalance: 再平衡 GBI/TBI(Robo)
    fe: api_key_management(數位雲)
    be: API key 註冊 (api_key_registry) API key 查詢 (api_key_query)(數位雲)
    setting: native的設定app
    cube_mock: cube mock

    main: 本線
    mock: mock server
    unstable: 自動化容易fail者
    dev: 開發中不要跑在任何情境上
    review: 準備要review的case
    positive: 正向
    negative: 負向
    tqa: tqa required items

    generate: 更新測報用
    precondition: 前置
    reg: 執行reg

    screenshot: 需檢查截圖
    zh: 中文版
    en: 英文版
    cangjie: ios17倉頡測案
    alert: AWS device farm ios alert
    aws
    skip_pre_login
    refactor:已經refactor的測案(目前為Android)

    cube_mock_pos: mock正向流程

    pending: 測向暫時不執行或還沒ready
    skip_pre_login: Skip the pre-login fixture for this test.
    stiuat
    ios:
        personal
        login_ihave
        password
        overview
    android_login
    gmb_login
    ios_login
    gmb_unlock

addopts = --strict-markers --tb=short --alluredir=./reports/allure_tmp